// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"encoding/json"
	"time"
)

const TableNameTaskM = "task"

// TaskM 任务表
type TaskM struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null;comment:任务名称" json:"name"`                       // 任务名称
	Namespace string    `gorm:"column:namespace;not null;comment:k8s namespace 名称" json:"namespace"` // k8s namespace 名称
	Info      TaskInfo  `gorm:"column:info;not null;comment:任务 k8s 相关信息" json:"info"`                // 任务 k8s 相关信息
	Status    string    `gorm:"column:status;not null;comment:任务状态" json:"status"`                   // 任务状态
	UserID    int64     `gorm:"column:user_id;not null;comment:用户 ID" json:"user_id"`                // 用户 ID
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:current_timestamp()" json:"updated_at"`
}

// TableName TaskM's table name
func (*TaskM) TableName() string {
	return TableNameTaskM
}

type TaskInfo struct {
	Image   string   `json:"image"`
	Command []string `json:"command"`
	Args    []string `json:"args"`
}

func (ti *TaskInfo) Scan(value any) error {
	if value == nil {
		return nil
	}
	return json.Unmarshal(value.([]byte), ti)
}

func (ti TaskInfo) Value() (driver.Value, error) {
	bytes, err := json.Marshal(ti)
	return string(bytes), err
}
